apiVersion: v1
kind: ServiceAccount
metadata:
  # this service account was created by azwi
  name: workload-identity-sa
  annotations:
    azure.workload.identity/client-id: 5e26c7ea-c6ee-4ebf-adac-8026d208d2b7
    azure.workload.identity/tenant-id: 38270d4e-aea5-4430-b2c7-1deb696ac290
