apiVersion: v1
kind: ServiceAccount
metadata:
  # this service account was created by azwi
  name: workload-identity-sa
  annotations:
    azure.workload.identity/client-id: 5fd3e44f-da1e-4bd7-9101-7938f782945d
    azure.workload.identity/tenant-id: 38270d4e-aea5-4430-b2c7-1deb696ac290
