apiVersion: v1
kind: ServiceAccount
metadata:
  # this service account was created by azwi
  name: workload-identity-sa
  annotations:
    azure.workload.identity/client-id: be2fe13f-38e8-49f9-b599-360e7818c5cc
    azure.workload.identity/tenant-id: 38270d4e-aea5-4430-b2c7-1deb696ac290
