{{- if .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "keycloak.fullname" . }}-cluster-role
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
rules:
  # Allow Keycloak to discover and validate Kubernetes API server endpoints
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch"]
  
  # Allow reading ConfigMaps for OIDC discovery
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  
  # Allow reading secrets for token validation
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
  
  # Allow reading services for service discovery
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch"]
  
  # Allow reading users and groups for RBAC integration
  - apiGroups: [""]
    resources: ["users", "groups"]
    verbs: ["get", "list", "watch"]
    resourceNames: []
  
  # Allow reading cluster roles and role bindings for RBAC mapping
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterroles", "clusterrolebindings", "roles", "rolebindings"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "keycloak.fullname" . }}-cluster-role-binding
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "keycloak.fullname" . }}-cluster-role
subjects:
  - kind: ServiceAccount
    name: {{ include "keycloak.serviceAccountName" . }}
    namespace: {{ .Values.global.namespace | default .Release.Namespace }}

---
# Role for managing Keycloak-specific resources in the namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "keycloak.fullname" . }}-role
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
rules:
  # Allow managing ConfigMaps for Keycloak configuration
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  
  # Allow managing Secrets for Keycloak credentials
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  
  # Allow managing Services for Keycloak exposure
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  
  # Allow managing PersistentVolumeClaims for Keycloak data
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  
  # Allow managing Pods for troubleshooting
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  
  # Allow managing Deployments for Keycloak
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  
  # Allow managing Ingress for Keycloak exposure
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "keycloak.fullname" . }}-role-binding
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "keycloak.fullname" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "keycloak.serviceAccountName" . }}
    namespace: {{ .Values.global.namespace | default .Release.Namespace }}

{{- if .Values.rbac.oidcIntegration.enabled }}
---
# ClusterRole for OIDC integration with Kubernetes API Server
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "keycloak.fullname" . }}-oidc-role
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
  annotations:
    keycloak.embracon.com/oidc-issuer: {{ include "keycloak.oidcIssuerUrl" . }}
    keycloak.embracon.com/client-id: {{ .Values.rbac.oidcIntegration.clientId }}
rules:
  {{- range .Values.rbac.oidcIntegration.clusterRoleRules }}
  - apiGroups: {{ .apiGroups | toJson }}
    resources: {{ .resources | toJson }}
    verbs: {{ .verbs | toJson }}
    {{- if .resourceNames }}
    resourceNames: {{ .resourceNames | toJson }}
    {{- end }}
    {{- if .nonResourceURLs }}
    nonResourceURLs: {{ .nonResourceURLs | toJson }}
    {{- end }}
  {{- end }}

---
# ClusterRoleBinding for OIDC groups
{{- range .Values.rbac.oidcIntegration.groupBindings }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "keycloak.fullname" $ }}-oidc-{{ .group | replace "/" "-" | replace " " "-" | lower }}
  labels:
    {{- include "keycloak.labels" $ | nindent 4 }}
  annotations:
    keycloak.embracon.com/group: {{ .group }}
    keycloak.embracon.com/description: {{ .description | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .clusterRole }}
subjects:
  - kind: Group
    name: {{ .group }}
    apiGroup: rbac.authorization.k8s.io
---
{{- end }}

{{- if .Values.rbac.oidcIntegration.namespaceBindings }}
# Namespace-specific role bindings for OIDC groups
{{- range .Values.rbac.oidcIntegration.namespaceBindings }}
{{- range $namespace := .namespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "keycloak.fullname" $ }}-oidc-{{ $.group | replace "/" "-" | replace " " "-" | lower }}
  namespace: {{ $namespace }}
  labels:
    {{- include "keycloak.labels" $ | nindent 4 }}
  annotations:
    keycloak.embracon.com/group: {{ $.group }}
    keycloak.embracon.com/namespace: {{ $namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ $.roleType }}
  name: {{ $.role }}
subjects:
  - kind: Group
    name: {{ $.group }}
    apiGroup: rbac.authorization.k8s.io
---
{{- end }}
{{- end }}
{{- end }}

{{- end }}
{{- end }}
