{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.adminSecretName" . }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.auth.usernameKey | default "username" }}: {{ .Values.auth.adminUser | b64enc | quote }}
  {{ .Values.auth.passwordKey | default "password" }}: {{ .Values.auth.adminPassword | b64enc | quote }}
{{- end }}
---
{{- if and (not .Values.postgresql.enabled) (not .Values.database.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}-database
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.database.usernameKey | default "username" }}: {{ .Values.database.username | b64enc | quote }}
  {{ .Values.database.passwordKey | default "password" }}: {{ .Values.database.password | b64enc | quote }}
{{- end }}
---
{{- if .Values.rbac.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}-oidc
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
data:
  client-id: {{ .Values.rbac.oidc.clientId | b64enc | quote }}
  client-secret: {{ .Values.rbac.oidc.clientSecret | b64enc | quote }}
  issuer-url: {{ include "keycloak.oidcIssuerUrl" . | b64enc | quote }}
{{- end }}
