apiVersion: v1
kind: Service
metadata:
  name: {{ include "embracon-app.fullname" . }}
  labels:
    {{- include "embracon-app.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
    {{- if .Values.monitoring.enabled }}
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "embracon-app.selectorLabels" . | nindent 4 }}
