name: Security Check with Snyk

on:
  workflow_call:
    inputs:
      dockerfile-path:
        required: true
        type: string
      context-path:
        required: true
        type: string
      project-name:
        required: true
        type: string
    secrets:
      SNYK_TOKEN:
        required: true

jobs:
  snyk-scan:
    name: Snyk Security Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker Build
        run: docker build -t snyk-python:latest -f ${{ inputs.dockerfile-path }} ${{ inputs.context-path }}

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate with Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk test
        run: snyk container test --docker snyk-python:latest --file=${{ inputs.dockerfile-path }}
        continue-on-error: true

      - name: Generate Snyk report
        run: snyk container monitor --docker snyk-python:latest --file=${{ inputs.dockerfile-path }} --project-name=${{ inputs.project-name }}
