name: Veracode Template v5

on:
  workflow_call:
    inputs:
      build-id:
        description: 'ID da build'
        required: true
        type: string

      # testes com project name - jose victor
      project_veracode:
        description: 'Project'
        required: true
        type: string

      environment:
        description: 'Environment'
        required: true
        type: string

      veracode_policy_name:
        description: 'Policy do Veracode'
        required: false
        type: string
        default: 'Embracon-Corporativa_SAST-SCA'

env:
  PROJECT: ${{ inputs.project_veracode }}
  ENVIRONMENT: ${{ inputs.environment }}

jobs:
  AutoPack:
    name: AutoPack
    runs-on:  ubuntu-24.04

    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

    ## Adiciona os passos para PHP se existir um composer.json ##
      #- name: Verificar se é projeto PHP
        #id: check_php
        #run: |
          #if [ -f "composer.json" ]; then
            #echo "::set-output name=exists::true"
          #else
            #echo "::set-output name=exists::false"
          #fi

      #- name: Configurar PHP
        #if: ${{ steps.check_php.outputs.exists == 'true' }}
        #uses: shivammathur/setup-php@v2
        #with:
          #php-version: '7.x'  # ou outra versão conforme sua necessidade

      #- name: Install dependencies
        #run: composer install --prefer-dist --no-progress

      - name: Detectar Projeto Java-Maven
        id: check_maven
        run: |
          if [ -f "pom.xml" ]; then
            echo "java_maven=true" >> $GITHUB_OUTPUT
          else
            echo "java_maven=false" >> $GITHUB_OUTPUT
          fi

      - name: Detectar versão do Java no pom.xml
        if: ${{ steps.check_maven.outputs.java_maven == 'true' }}
        id: detect_java
        run: |
          # Tenta extrair o valor de <maven.compiler.source> do pom.xml
          JAVA_VERSION=$(grep -oPm1 "(?<=<maven.compiler.source>)[^<]+" pom.xml || echo "11")
          if [[ "$JAVA_VERSION" == "11" ]]; then
            JAVA_VERSION=$(grep -oPm1 "(?<=<java.version>)[^<]+" pom.xml || echo "11")
          fi
          if [[ "$JAVA_VERSION" == "\${java.version}" ]]; then
            JAVA_VERSION=$(grep -oPm1 "(?<=<java.version>)[^<]+" pom.xml || echo "11")
          fi
          echo "Versão do Java detectada: $JAVA_VERSION"
          echo "java_version=$JAVA_VERSION" >> $GITHUB_OUTPUT

      - name: Configurar JDK e Maven
        if: ${{ steps.check_maven.outputs.java_maven == 'true' }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ steps.detect_java.outputs.java_version }}
          distribution: 'temurin'
          cache: maven

      - name: Compilar Projeto Maven
        if: ${{ steps.check_maven.outputs.java_maven == 'true' }}
        run: mvn clean package -DskipTests

      - name: Instalar CLI do Veracode e Autopack-Veracode
        run: |
          mkdir -p ${{ github.workspace }}/artifacts/${{ inputs.build-id }}
      
          # Procura por arquivos WAR, JAR ou ZIP na pasta target
          WAR_FILE=$(find target/ -maxdepth 1 -name "*.war" | head -n 1)
          JAR_FILE=$(find target/ -maxdepth 1 -name "*.jar" | head -n 1)
      
          if [ -f "$WAR_FILE" ]; then
            echo "WAR encontrado: $WAR_FILE"
            # Copia o WAR para o diretório de artefatos com um nome fixo
            cp "$WAR_FILE" ${{ github.workspace }}/artifacts/${{ inputs.build-id }}/application.war
      
          elif [ -f "$JAR_FILE" ]; then
            echo "JAR encontrado: $JAR_FILE"
            cp "$JAR_FILE" ${{ github.workspace }}/artifacts/${{ inputs.build-id }}/application.jar
            # Compacta o JAR em um zip para padronizar, se necessário
      
          else
            echo "Nenhum WAR, JAR ou ZIP encontrado. Rodando Autopack..."
            curl -fsS https://tools.veracode.com/veracode-cli/install | sh
            ./veracode package --source . --output ${{ github.workspace }}/artifacts/${{ inputs.build-id }} --trust
      
            find ${{ github.workspace }}/artifacts/${{ inputs.build-id }} -name "*.zip" |
            while read filename; do unzip -o -d "$(dirname "$filename")" "$filename"; done
      
            rm -rf ${{ github.workspace }}/artifacts/${{ inputs.build-id }}/*.zip
            zip analysisPack.zip -r ${{ github.workspace }}/artifacts/${{ inputs.build-id }}
            mv analysisPack.zip ${{ github.workspace }}/artifacts/${{ inputs.build-id }}/analysisPack.zip
          fi

      - name: Publicar Artefato para Análise
        uses: actions/upload-artifact@v4
        with:
          name: analysisPack
          path: |
            ${{ github.workspace }}/artifacts/${{ inputs.build-id }}/analysisPack.zip
            ${{ github.workspace }}/artifacts/${{ inputs.build-id }}/application.jar
            ${{ github.workspace }}/artifacts/${{ inputs.build-id }}/application.war
            
          retention-days: 1

  SCA:
    name: SCA
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Executar Veracode SCA
        continue-on-error: true
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SCA }}
        run: |
          curl -sSL https://download.sourceclear.com/ci.sh | bash -s – scan --update-advisor --allow-dirty

  Scan:
    name: Scan
    runs-on: ubuntu-24.04
    needs: AutoPack
    
    steps:
      # 1) Baixa o artifact com nome 'analysisPack'
      - name: Baixar Artefato para Análise
        uses: actions/download-artifact@v4
        with:
          name: analysisPack
  
      # 2) (Opcional) Listar arquivos baixados para confirmar o que veio
      
  
      # 3) Detectar qual arquivo usar (WAR/JAR ou analysisPack.zip)
      - name: Detectar arquivo de análise
        id: detect_artifact
        run: |
          # Procura pelo arquivo WAR
          WAR_FILE=$(find . -name "*.war" | head -n 1)
          # Procura pelo arquivo JAR (excluindo o pipeline-scan.jar)
          JAR_FILE=$(find . -name "*.jar" -not -name "pipeline-scan.jar" | head -n 1)
  
          if [ -f "$WAR_FILE" ]; then
            echo "WAR encontrado: $WAR_FILE"
            echo "artifact_file=$WAR_FILE" >> $GITHUB_OUTPUT
          elif [ -f "$JAR_FILE" ]; then
            echo "JAR encontrado: $JAR_FILE"
            echo "artifact_file=$JAR_FILE" >> $GITHUB_OUTPUT
          else
            if [ -f "analysisPack.zip" ]; then
              echo "Nenhum WAR/JAR encontrado. Usando analysisPack.zip."
              echo "artifact_file=analysisPack.zip" >> $GITHUB_OUTPUT
            else
              echo "Erro: Nenhum WAR/JAR ou analysisPack.zip"
            fi
          fi

      - name: Policy Name Substitution
        id: policy-name-sub
        run: |
        
            # Setar policy default
            echo "policy_veracode_sub=${{ inputs.veracode_policy_name }}" >> "$GITHUB_OUTPUT"
            
            # Forçar policy 
            declare -A POLICY_MAP
            POLICY_MAP["transferenciacota-api"]="Embracon-transferenciacota-api"
            POLICY_MAP["hierarquia-service"]="Embracon-hierarquia_boavista"
            POLICY_MAP["embrapay-api"]="Embracon-Corporativa_SAST-SCA"
            POLICY_MAP["embrapay-front"]="Embracon-Corporativa_SAST-SCA"
            POLICY_MAP["clientereides"]="Embracon-clientereides"
            POLICY_MAP["clientereihom"]="Embracon-clientereides"
            POLICY_MAP["clientereiprod"]="Embracon-clientereides"
            POLICY_MAP["boavistaapi"]="Embracon-hierarquia_boavista"
            POLICY_MAP["extratocota-service"]="Embracon-Corporativa"
            POLICY_MAP["embraconutils"]="Embracon-Corporativa"
            POLICY_MAP["mapacomissaoservice"]="Embracon-mapacomissaoservice-api"
            POLICY_MAP["nomedoprojeto-api"]="nomedapolicy"
            POLICY_MAP["logindes"]="Embracon-login-api"
            POLICY_MAP["simulacreditodes"]="Embracon-simulacredito-api"
            POLICY_MAP["simulacreditohom"]="Embracon-simulacredito-api"
            POLICY_MAP["simulacreditoprod"]="Embracon-simulacredito-api"
            POLICY_MAP["embracon-api"]="Embracon-embracon-api"
            POLICY_MAP["embrapagdes"]="Embracon-embrapag-api"
            POLICY_MAP["embrapaghom"]="Embracon-embrapag-api"
            POLICY_MAP["embrapagprod"]="Embracon-embrapag-api"
            POLICY_MAP["area-restrita-api"]="Embracon-area-restrita-api"
            POLICY_MAP["evento-cotades"]="Embracon-Corporativa"
            POLICY_MAP["boleto-service"]="Embracon-Corporativa"
            POLICY_MAP["documentos-api"]="Embracon-Corporativa"
            POLICY_MAP["logs-backend"]="Embracon-logs-backend"
            POLICY_MAP["gebol-captcha"]="Embracon-gebol-captcha-api" 
            POLICY_MAP["gebol-business"]="Embracon-gebol-business-api" 
            POLICY_MAP["gebol-core"]="Embracon-gebol-core-api"
            POLICY_MAP["processarslipjob"]="Embracon-Corporativa"
            POLICY_MAP["procon"]="Embracon-Corporativa"
            POLICY_MAP["assinaturaeletronica"]="Embracon-assinaturaeletronica-api"
            POLICY_MAP["integracao-api"]="Embracon-integracao-api"
            POLICY_MAP["baasrw"]="Embracon-baas_baasrw"
            POLICY_MAP["geradorboleto-api"]="Embracon-geradorboleto-api"
            POLICY_MAP["rating-api"]="Embracon-rating-api"
            POLICY_MAP["sender-marketingcloud-api"]="Embracon-sender-marketingcloud-api"
            POLICY_MAP["portal-corretora"]="Embracon-portal-corretora-api"
            POLICY_MAP["integracaosf"]="Embracon-integracaosf-api"
            POLICY_MAP["embracon-api-assembleia"]="Embracon-Corporativa_SAST-SCA"
            POLICY_MAP["embracon-api-pagamentos"]="Embracon-Corporativa_SAST-SCA"
            POLICY_MAP["embracon-api-login"]="Embracon-Corporativa_SAST-SCA"
            POLICY_MAP["embracon-api-vendas"]="Embracon-Corporativa_SAST-SCA"
            POLICY_MAP["embracon-api-clientes"]="Embracon-Corporativa_SAST-SCA"
            POLICY_MAP["embracon-api-consumer"]="Embracon-Corporativa_SAST-SCA"
            POLICY_MAP["embracon-api-extrato-cota"]="Embracon-Corporativa_SAST-SCA"
            POLICY_MAP["embracon-api-simulacoes"]="Embracon-Corporativa_SAST-SCA"
            POLICY_MAP["embracon-api-sender"]="Embracon-Corporativa_SAST-SCA"
            POLICY_MAP["file-service-api"]="Embracon-Corporativa_SAST-SCA"
            POLICY_MAP["autorizador-service-api"]="Embracon-Corporativa_SAST-SCA"
            POLICY_MAP["autentica-sistemas-api"]="Embracon-Corporativa_SAST-SCA"
            POLICY_MAP["gebol-frontend"]="Embracon-gebol-frontend"
            POLICY_MAP["assinaturaeletronica-admin"]="Embracon-assinaturaeletronica-admin"
            POLICY_MAP["clienterei-frontend"]="Embracon-clienterei-frontend"
            POLICY_MAP["reset-senha-front"]="Embracon-reset-senha-front"
            POLICY_MAP["compliance"]="Embracon-compliance"
            POLICY_MAP["geradorboleto-web"]="Embracon-GeradorBoleto_WebatendFront"
            POLICY_MAP["transferenciacota-front"]="Embracon-transferenciacota-front"
            POLICY_MAP["rating-web"]="Embracon-rating-web"
            POLICY_MAP["portaldocumentacao-frontend"]="Embracon-portaldocumentacao-frontend_logsfrontend"
            POLICY_MAP["file-service-dev"]="Embracon-file-service"
            POLICY_MAP["file-service-hom"]="Embracon-file-service"
            POLICY_MAP["file-service-prod"]="Embracon-file-service"
            POLICY_MAP["webatendimento-api"]="Embracon-webatendimentointegration_webatendimentoapi"
            POLICY_MAP["webatendimento-integration-support"]="Embracon-webatendimentointegration_webatendimentoapi"
            POLICY_MAP["embracon-webatendimento-frontend-partner-customization"]="Embracon-Corporativa"
            POLICY_MAP["webatendimento-pwa"]="Embracon-GeradorBoleto_WebatendFront"
            POLICY_MAP["portal-corretora-front"]="Embracon-CorretoraFront"
            POLICY_MAP["baas"]="Embracon-baas_baasrw"
            POLICY_MAP["simplimais-api"]="Embracon-Corporativa_SAST-SCA"
            POLICY_MAP["simplimais"]="Embracon-Corporativa_SAST-SCA"
            
            
            
            if [[ ${POLICY_MAP[${{ inputs.project_veracode }}]} != "" ]]; then
                echo "Forçar policy de ${{ inputs.veracode_policy_name }} para ${POLICY_MAP[${{ inputs.project_veracode }}]}"
                echo "policy_veracode_sub=${POLICY_MAP[${{ inputs.project_veracode }}]}" >> "$GITHUB_OUTPUT"
            fi

      # 4) Executa o Pipeline Scan usando o arquivo detectado
      - name: Executar Veracode Pipeline Scan
        uses: veracode/Veracode-pipeline-scan-action@v1.0.18
        with:
          vid: ${{ secrets.APIID_VERACODE }}
          vkey: ${{ secrets.APIKEY_VERACODE }}
          file: ${{ steps.detect_artifact.outputs.artifact_file }} --issue_details true
          veracode_policy_name: ${{ steps.policy-name-sub.outputs.policy_veracode_sub }}
          #fail_build: true
          fail_build: ${{ inputs.environment == 'prod' }}

  SAST:
    runs-on: ubuntu-24.04
    needs: AutoPack
    steps:
      - name: Baixar Artefato para Análise SAST
        uses: actions/download-artifact@v4
        with:
          name: analysisPack

      - name: Baixar Veracode SAST Wrapper
        run: |
          curl -O -L https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/24.7.14.0/vosp-api-wrappers-java-24.7.14.0.jar

      - name: Project Name Substitution
        id: project-name-sub
        run: |
          # Caso projeto não esteja no map, utiliza o nome padrão
          echo "project_veracode_sub=${{ inputs.project_veracode }}" >> "$GITHUB_OUTPUT"
          
          # Criar o mapeamento de nomes dos projetos
          declare -A PROJECT_MAP
          PROJECT_MAP["nomeprojetozuado"]="novonomeprojeto"
          PROJECT_MAP["nomeprojetozuado02"]="novonomeprojeto02"
          PROJECT_MAP["simulacreditodes"]="simulacredito-api"
          PROJECT_MAP["simulacreditohom"]="simulacredito-api"
          PROJECT_MAP["simulacreditoprod"]="simulacredito-api"
          PROJECT_MAP["embrapagdes"]="embrapag-api"
          PROJECT_MAP["embrapaghom"]="embrapag-api"
          PROJECT_MAP["embrapagprod"]="embrapag-api"
          PROJECT_MAP["portal-corretora"]="portal-corretora-api"
          PROJECT_MAP["mapacomissaoservice"]="mapacomissaoservice-api"
          PROJECT_MAP["boavistaapi"]="boavista-api"
          PROJECT_MAP["evento-cotades"]="evento-cota-api"
          PROJECT_MAP["extratocota-service"]="extratocota-service-api"
          PROJECT_MAP["hierarquia-service"]="hierarquia-service-api"
          PROJECT_MAP["procon"]="procon-api"
          PROJECT_MAP["embraconutils"]="embraconutils-api"
          PROJECT_MAP["logindes"]="login-api" 
          PROJECT_MAP["gebol-captcha"]="gebol-captcha-api" 
          PROJECT_MAP["gebol-business"]="gebol-business-api" 
          PROJECT_MAP["gebol-core"]="gebol-core-api" 
          PROJECT_MAP["assinaturaeletronica"]="assinaturaeletronica-api" 
          PROJECT_MAP["integracaosf"]="integracaosf-api"
          PROJECT_MAP["portal-corretora"]="portal-corretora-api"
          PROJECT_MAP["webatendimento-integration-support"]="webatendimento-integration"
          PROJECT_MAP["embracon-webatendimento-frontend-partner-customization"]="embracon-webatendimento-admin"
          PROJECT_MAP["webatendimento-pwa"]="webatendimento-frontend"
          PROJECT_MAP["file-service-dev"]="file-service"
          PROJECT_MAP["file-service-hom"]="file-service"
          PROJECT_MAP["file-service-prod"]="file-service"
          PROJECT_MAP["clientereides"]="clienterei-api"
          PROJECT_MAP["clientereihom"]="clienterei-api"
          PROJECT_MAP["clientereiprod"]="clienterei-api"
          
           
          ##PROJECT_MAP["project"]="name"
                    
          
          # Setar o nome do projeto, se houver mapeamento
          if [[ ${PROJECT_MAP[${{ inputs.project_veracode }}]} != "" ]]; then
            echo "Definindo novo nome para de ${{ inputs.project_veracode }} para ${PROJECT_MAP[${{ inputs.project_veracode }}]}"
            echo "project_veracode_sub=${PROJECT_MAP[${{ inputs.project_veracode }}]}" >> "$GITHUB_OUTPUT"
          fi

      - name: Read Project Name Substitution
        run: echo "${{ steps.project-name-sub.outputs.project_veracode_sub }}"

      - name: Executar Veracode SAST
        env:
          VID: ${{ secrets.APIID_VERACODE }}
          VKEY: ${{ secrets.APIKEY_VERACODE }}
          ENVIRONMENT: ${{ inputs.environment }}
        run: |
          # Verifica se existe um WAR
          WAR_FILE=$(find . -maxdepth 2 -name "*.war" | head -n 1)
          if [ -f "$WAR_FILE" ]; then
            echo "Aplicação WAR detectada. Usando arquivo: $WAR_FILE"
            ARTIFACT="$WAR_FILE"
          else
            # Procura por um JAR (excluindo o vosp-api-wrappers)
            JAR_FILE=$(find . -maxdepth 2 -name "*.jar" -not -name "vosp-api-wrappers*.jar" | head -n 1)
            if [ -f "$JAR_FILE" ]; then
              echo "Java build detectado. Usando arquivo: $JAR_FILE"
              ARTIFACT="$JAR_FILE"
            else
              echo "Nenhum WAR ou JAR encontrado. Usando analysisPack.zip."
              ARTIFACT="analysisPack.zip"
            fi
          fi
      
          if [ "$ENVIRONMENT" == "prod" ]; then
            echo "Executando SAST em ambiente de produção..."
            java -jar vosp-api-wrappers-java-24.7.14.0.jar \
              -vid $VID -vkey $VKEY \
              -action uploadandscan \
              -appname "${{ steps.project-name-sub.outputs.project_veracode_sub }}" \
              -version "${{ inputs.build-id }}" \
              -filepath "$ARTIFACT" \
              -createprofile true \
              -deleteincompletescan 2 \
              -createsandbox false
          else
            echo "Executando SAST em ambiente de sandbox..."
            java -jar vosp-api-wrappers-java-24.7.14.0.jar \
              -vid $VID -vkey $VKEY \
              -action uploadandscan \
              -appname "${{ steps.project-name-sub.outputs.project_veracode_sub }}" \
              -version "${{ inputs.build-id }}" \
              -filepath "$ARTIFACT" \
              -createprofile true \
              -deleteincompletescan 2 \
              -createsandbox true \
              -sandboxname "$ENVIRONMENT" \
              -debug
          fi
