apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak.fullname" . }}-config
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
data:
  {{- if .Values.keycloak.extraConfig }}
  keycloak.conf: |
    {{- .Values.keycloak.extraConfig | nindent 4 }}
  {{- end }}
  realm-import.json: |
    {{- if .Values.realmImport.enabled }}
    {
      "realm": "{{ .Values.realmImport.realm.realm }}",
      "displayName": "{{ .Values.realmImport.realm.displayName }}",
      "enabled": {{ .Values.realmImport.realm.enabled }},
      "sslRequired": "{{ .Values.realmImport.realm.sslRequired }}",
      "registrationAllowed": {{ .Values.realmImport.realm.registrationAllowed }},
      "resetPasswordAllowed": {{ .Values.realmImport.realm.resetPasswordAllowed }},
      "editUsernameAllowed": {{ .Values.realmImport.realm.editUsernameAllowed }},
      "bruteForceProtected": {{ .Values.realmImport.realm.bruteForceProtected }},
      "groups": [
        {{- range $index, $group := .Values.realmImport.realm.groups }}
        {{- if $index }},{{ end }}
        {
          "name": "{{ $group.name }}",
          "path": "/{{ $group.name }}",
          "subGroups": [
            {{- range $subIndex, $subGroup := $group.subGroups }}
            {{- if $subIndex }},{{ end }}
            {
              "name": "{{ $subGroup.name }}",
              "path": "/{{ $group.name }}/{{ $subGroup.name }}"
            }
            {{- end }}
          ]
        }
        {{- end }}
      ],
      "clients": [
        {{- range $index, $client := .Values.realmImport.realm.clients }}
        {{- if $index }},{{ end }}
        {
          "clientId": "{{ $client.clientId }}",
          "name": "{{ $client.name }}",
          "enabled": {{ $client.enabled }},
          "protocol": "{{ $client.protocol }}",
          "publicClient": {{ $client.publicClient }},
          "bearerOnly": {{ $client.bearerOnly }},
          "standardFlowEnabled": {{ $client.standardFlowEnabled }},
          "directAccessGrantsEnabled": {{ $client.directAccessGrantsEnabled }},
          "secret": "{{ $client.secret }}",
          "redirectUris": [
            {{- range $uriIndex, $uri := $client.redirectUris }}
            {{- if $uriIndex }},{{ end }}
            "{{ $uri }}"
            {{- end }}
          ],
          "webOrigins": [
            {{- range $originIndex, $origin := $client.webOrigins }}
            {{- if $originIndex }},{{ end }}
            "{{ $origin }}"
            {{- end }}
          ],
          "protocolMappers": [
            {
              "name": "groups",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-group-membership-mapper",
              "consentRequired": false,
              "config": {
                "full.path": "false",
                "id.token.claim": "true",
                "access.token.claim": "true",
                "claim.name": "groups",
                "userinfo.token.claim": "true"
              }
            }
          ]
        }
        {{- end }}
      ]
    }
    {{- end }}
