apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: dev
    environment: development
    project: embracon-toolbox
  annotations:
    description: "Namespace para desenvolvimento e testes de RBAC com External Secrets"
