apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: dev
spec:
  serviceAccountName: app-alpha-sa  # Nossa SA (sem permissão get secrets)
  containers:
  - name: test-container
    image: nginx:alpine
    
    # MÉTODO 1: Environment Variables
    env:
    - name: MY_SECRET_VALUE
      valueFrom:
        secretKeyRef:
          name: rbac-test-secret-k8s-akv  # Secret criado pelo ESO
          key: my-akv-secret-key
    
    # MÉTODO 2: Volume Mount
    volumeMounts:
    - name: secret-volume
      mountPath: "/etc/secrets"
      readOnly: true
    
    # Para testar
    command: ["/bin/sh"]
    args: ["-c", "echo 'Secret via ENV:' && echo $MY_SECRET_VALUE && echo 'Secret via file:' && cat /etc/secrets/my-akv-secret-key && echo 'Files in /etc/secrets/:' && ls -la /etc/secrets/ && sleep 3600"]
  
  volumes:
  - name: secret-volume
    secret:
      secretName: rbac-test-secret-k8s-akv
  
  restartPolicy: Never
