apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
  namespace: dev
rules:
# Permissão para acessar APENAS o secret específico que você definiu
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["rbac-test-secret-k8s-akv"]  # APENAS este secret
  verbs: ["get", "watch", "list"]