---
# Exemplo de manifesto do ExternalSecret para consumir uma secret do Google Secret Manager (GCP) usando SecretStore e criar uma secret no Kubernetes.
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: exemplo-gcp
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: SecretStore
  target:
    name: minha-secret-no-k8s
    creationPolicy: Owner
  data:
    - secretKey: minha-chave-no-k8s
      remoteRef:
        key: embracon