apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: exemplo-akv
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  target:
    name: minha-secret-no-k8s
    creationPolicy: Owner
  data:
    - secretKey: minha-chave-no-k8s
      remoteRef:
        key: nome-da-secret-no-akv
