apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gcp-secret-manager-store
  namespace: default
spec:
  retrySettings:
    maxRetries: 5
    retryInterval: "10s"
  provider:
    gcpsm:
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcp-secret-manager-credentials
            key: credentials.json
      projectID: shared-vpc-host-454114