apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gcp-secret-store
  namespace: default
spec:
  retrySettings:
    maxRetries: 5
    retryInterval: "10s"
  provider:
    gcpsm:
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcp-sa-secret
            key: sa-key-secret-manager.json
      projectID: shared-vpc-host-454114