apiVersion: v1
kind: ServiceAccount
metadata:
  # this service account was created by azwi
  name: workload-identity-sa
  annotations:
    azure.workload.identity/client-id: d52de8f1-4a6d-4fc7-b670-f9e1202854b1
    azure.workload.identity/tenant-id: 38270d4e-aea5-4430-b2c7-1deb696ac290
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: akv-secret-manager-store
  namespace: default
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://k8s-keys.vault.azure.net/"
      serviceAccountRef:
        name: workload-identity-sa
