name: Reusable Build and Push Docker Image

on:
    workflow_call:
        inputs:
            app_context:
                required: true
                type: string
                description: 'Path to the application context (e.g., app/python, app/nodejs, app/java)'
            app_tags:
                required: true
                type: string
                description: 'Tags to apply to the Docker image (e.g., latest, stable)'
            dck_username:
                required: true
                type: string
                description: 'Docker Hub username for authentication'
        secrets:
            dck_token:
                required: true
                description: 'Docker Hub token for authentication'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ inputs.dck_username }}
                password: ${{ secrets.dck_token }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                context: ${{ inputs.app_context }}
                push: true
                tags: ${{ inputs.app_tags }}
                cache-from: type=gha
                cache-to: type=gha,mode=max
