name: Reusable Gitleaks Workflow

on:
    workflow_call:
        inputs:
            gitleaks-version:
                required: false
                type: string
                default: "latest"
        secrets:
            TOKEN:
                required: true
            LICENSE:
                required: false

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2

        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.LICENSE }} # Only required for Organizations, not personal accounts.
