name: Node CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'app/nodejs/**'
  workflow_dispatch:
    inputs:
      gitleaks-version:
        description: 'Version of Gitleaks to use'
        required: false
        default: 'latest'

jobs:

  test:
    uses: ./.github/workflows/reusable.yml
    with:
      gitleaks-version: 'latest'
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}  # Only required for Organizations, not personal accounts.
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      working-directory: app/nodejs  # Ensure you are in the right directory
      run: npm install

    - name: Build Docker image
      working-directory: app/nodejs
      run: docker build -t nodejs-ci-cd .

    - name: Install Trivy
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
        sudo mv ./bin/trivy /usr/local/bin/trivy  # Move Trivy to a location in the PATH

    - name: Run Trivy to scan Docker image for vulnerabilities
      run: |
        trivy image nodejs-ci-cd
