name: Executar Azure CLI Login com OpenID Connect
on: [workflow_dispatch]

jobs:
  test:
    permissions:
      id-token: write # Permissão necessária para buscar o token OIDC.
    runs-on: ubuntu-latest
    steps:
    - name: Azure CLI Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show
          # Você pode adicionar outros comandos Azure CLI aqui.