name: Reusable Trivy Workflow

on:
    workflow_call:
        inputs:
            docker_image:
                required: true
                type: string
        
jobs:
    trivy:
        runs-on: ubuntu-latest  # Executa em uma VM Ubuntu mais recente

        steps:
        - name: Checkout code  # Passo para baixar o código do repositório
          uses: actions/checkout@v3

        - name: Cache Trivy binary  # Cacheia o binário do Trivy
          id: cache-trivy
          uses: actions/cache@v3
          with:
            path: ./bin/trivy
            key: trivy-${{ runner.os }}-v0.50.2  # Atualize a versão conforme necessário

        - name: Install Trivy  # Instala o Trivy se não estiver em cache
          if: steps.cache-trivy.outputs.cache-hit != 'true'
          run: |
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh

        - name: Run Trivy to scan Docker image for vulnerabilities  # Executa o Trivy para escanear a imagem Docker
          run: |
            trivy image ${{ inputs.docker_image }}  # Escaneia a imagem especificada