name: Reusable Trivy Workflow

on:
    workflow_call:
        inputs:
            docker_image:
                required: true
                type: string
        
jobs:
    trivy:
        runs-on: ubuntu-latest  # Executa em uma VM Ubuntu mais recente

        steps:
         - name: Run Trivy vulnerability scanner
           uses: aquasecurity/trivy-action@0.28.0
           with:
             image-ref: ${{ inputs.docker_image }}
             format: 'table'
             exit-code: '1'
             ignore-unfixed: true
             vuln-type: 'os,library'
             severity: 'CRITICAL,HIGH'